NDefines.NCountry.CORRUPTION_FROM_BANNERS = 2
NDefines.NMilitary.BANNER_DISCIPLINE_BONUS = -0.05
NDefines.NMilitary.BANNER_MANPOWER_USAGE = 0
NDefines.NMilitary.BANNER_REINFORCE_SPEED = 0.25
NDefines.NMilitary.BANNER_MAINTENANCE_COST = 3
NDefines.NMilitary.BANNER_AGE_MULTIPLIER = 0
NDefines.NMilitary.BANNER_STARTING_STRENGTH = 0.1
NDefines.NMilitary.BANNER_USES_CONSTRUCTION = 0



NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 105
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 15
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0


NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 4
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = 0
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 40
NDefines.NCountry.PS_NAVAL_BARRAGE = 40
NDefines.NCountry.NOMAD_DEVELOPMENT_SCALE = 1000
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 100
NDefines.NCountry.MINIMUM_POLICY_TIME = 5


NDefines.NEconomy.CARAVAN_FACTOR = 3
NDefines.NEconomy.CARAVAN_POWER_MAX = 25
NDefines.NEconomy.CARAVAN_POWER_MIN = 2
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 25
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30

NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 0.7
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40
NDefines.NMilitary.MERCENARY_COMPANY_BUILDING_TIME = 0.4
NDefines.NMilitary.SLACKEN_MANPOWER_INCREASE = 1.0


NDefines.NReligion.MAX_CHURCH_POWER = 300
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.STARTING_HARMONY = 50.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 1.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -3.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.03
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0
